language: python
python:
  - "3.5"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install gevent; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install twisted; fi
  - python setup.py install
  - pip install coveralls
  - pip install coverage
  - pip install nose
  - pip install tornado
  - pip install gi
# command to run tests, e.g. python setup.py test
script:  coverage run --source=rx setup.py test
after_success:
  coveralls
