matrix:
  include:

    - name: "Python 3.6 on Linux"
      python: "3.6"
      os: linux
      dist: xenial
      language: python

    - name: "Python 3.7 on Linux"
      python: "3.7"
      os: linux
      dist: xenial
      language: python

    - name: "Python 3.8-dev on Linux"
      python: "3.8-dev"
      os: linux
      dist: xenial
      language: python

    - name: "Python 3.7 on Linux, with optional dependencies and benchmark"
      python: "3.7"
      os: linux
      dist: xenial
      language: python
      install:
        # Native libraries for pycairo / pygobject
        - sudo apt-get install -y libgirepository1.0-dev gir1.2-gtk-3.0
        # Pre-built wheel for wxpython
        - pip3 install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxpython
        # Install the various optional packages
        - pip3 install eventlet gevent pycairo pygobject pygame pyqt5 pyside2 tornado twisted
        # Coverage will be reported for the Python 3.7 Linux build
        - pip3 install coveralls
      script:
        - coverage run --source=rx setup.py test && coveralls

# Disable MacOS build temporarily, it's failing often on timing assertions
#    - name: "Python 3.7 on MacOS, with optional dependencies and benchmark"
#      python: "3.7"
#      os: osx
#      osx_image: xcode10.2
#      language: sh
#      install:
#        # Native libraries for pycairo / pygobject
#        - brew install pygobject3 gtk+3
#        # Install the various optional packages
#        - pip3 install eventlet gevent pycairo pygobject pygame pyqt5 pyside2 tornado twisted wxpython

    - name: "Python 3.7 on Windows, with optional dependencies and benchmark"
      python: "3.7"
      os: windows
      language: sh
      install:
        # Get Python 3.7 from choco
        - choco install python3
        - ln -s "/c/Python37/python.exe" "/c/Python37/python3.exe"
        - export PATH="/c/Python37/:/c/Python37/Scripts/:$PATH"
        # Install the various optional packages
        - pip3 install eventlet gevent pygame pyqt5 pyside2 tornado twisted wxpython
        # TODO install pycairo and pygobject somehow?

script:
  - python3 setup.py test

after_success:
  # Run a crude benchmark (unit tests minus test_scheduler) a couple of times.
  # Need to make a copy of the script first, because on Windows it disappears
  # whilst switching git branches.
  - if [[ $TRAVIS_JOB_NAME == *benchmark ]]; then
      pip3 install pytest>=4.4.1 pytest-asyncio>=0.10.0;
      cp ./.travis/bench.sh bench.sh && ./bench.sh;
    fi
